<?php

declare(strict_types=1);

namespace DevColorz;

/**
 * Installation secrets and paths.
 *
 * `config.php` is a PHP file that *returns* an array rather than a `.env` or a
 * JSON blob. If the deny rules ever fail, a served `.env` hands over every
 * secret in plain text, while a served `.php` file executes and outputs
 * nothing. Cheap insurance.
 */
final class Config
{
    /** @var array<string, mixed>|null */
    private static ?array $data = null;

    /** @return array<string, mixed> */
    public static function all(): array
    {
        if (self::$data !== null) {
            return self::$data;
        }
        $file = Paths::configFile();
        if (!is_file($file)) {
            self::$data = [];
            return self::$data;
        }
        /** @var mixed $loaded */
        $loaded = require $file;
        self::$data = is_array($loaded) ? $loaded : [];
        return self::$data;
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        return self::all()[$key] ?? $default;
    }

    public static function string(string $key, string $default = ''): string
    {
        $value = self::get($key);
        return is_string($value) ? $value : $default;
    }

    public static function installed(): bool
    {
        return is_file(Paths::configFile()) && self::string('db_file') !== '';
    }

    public static function dbPath(): string
    {
        $file = self::string('db_file');
        return $file !== '' ? Paths::storage() . '/' . $file : '';
    }

    /**
     * Write config.php atomically.
     *
     * `rename()` on the same filesystem is atomic, so a request arriving
     * mid-write never sees a truncated config — which would otherwise look
     * exactly like "not installed" and re-open the installer.
     *
     * @param array<string, mixed> $data
     */
    public static function write(array $data): void
    {
        $export = var_export($data, true);
        $body = "<?php\n\n"
            . "// DevColorz installation config — generated by install.php.\n"
            . "// Contains secrets. Never commit this file, never serve it.\n\n"
            . "return {$export};\n";

        $file = Paths::configFile();
        $temp = $file . '.' . bin2hex(random_bytes(6)) . '.tmp';
        if (file_put_contents($temp, $body, LOCK_EX) === false) {
            throw new \RuntimeException('Could not write config.php');
        }
        @chmod($temp, 0640);
        if (!rename($temp, $file)) {
            @unlink($temp);
            throw new \RuntimeException('Could not move config.php into place');
        }
        self::$data = $data;
    }

    /** Forget the cached copy — used by the installer after writing. */
    public static function reset(): void
    {
        self::$data = null;
    }

    /**
     * A fresh set of installation secrets.
     *
     * @return array<string, string>
     */
    public static function freshSecrets(): array
    {
        return [
            'db_file'      => '.ht' . bin2hex(random_bytes(16)) . '.sqlite',
            'app_key'      => bin2hex(random_bytes(32)),
            'hmac_key'     => bin2hex(random_bytes(32)),
            'pepper'       => bin2hex(random_bytes(32)),
            'cron_token'   => bin2hex(random_bytes(24)),
            'invite_token' => self::readableToken(),
        ];
    }

    /**
     * A token a human has to read off a screen and type into a form.
     *
     * Crockford's alphabet: no I, L, O or U, so it survives being read aloud,
     * written down, and typed by someone who has never seen it before.
     */
    public static function readableToken(int $groups = 4, int $size = 5): string
    {
        $alphabet = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
        $parts = [];
        for ($g = 0; $g < $groups; $g++) {
            $chunk = '';
            for ($i = 0; $i < $size; $i++) {
                $chunk .= $alphabet[random_int(0, strlen($alphabet) - 1)];
            }
            $parts[] = $chunk;
        }
        return implode('-', $parts);
    }
}
