/**
 * Output formats.
 *
 * Every emitter takes the same `TokenGraph` and returns text, so adding a
 * format cannot change which tokens exist — only how they are written down.
 */

import { formatColor, hexToken, toRgb } from '@/lib/color/convert'
import { bestBlackOrWhite, wcagLevel } from '@/lib/color/contrast'
import type { Oklch } from '@/lib/color/types'
import type { ExportConfig } from './config'
import { composeName, type Token, type TokenGraph } from './graph'

export interface EmittedFile {
  /** Path relative to the project, as the platform expects it. */
  path: string
  content: string
}

export interface Emitter {
  id: string
  label: string
  /** File extension, without the dot. */
  ext: string
  language: string
  /** One line explaining when to reach for this format. */
  hint: string
  /** The output as one readable text, for the panel and the clipboard. */
  emit(graph: TokenGraph): string
  /**
   * The output as the files it actually has to be split into, for downloads.
   * Only formats whose target cannot take one file define this — Android
   * keeps day and night values in two files that are each one XML document,
   * and saved as a single file the pair is not well-formed.
   */
  files?(graph: TokenGraph): EmittedFile[]
}

/**
 * The files an emitter produces, for a format that needs more than one.
 *
 * The default download is the single text `emit` returns, under the emitter's
 * own extension.
 */
export function emittedFiles(emitter: Emitter, graph: TokenGraph, stem: string): EmittedFile[] {
  return emitter.files?.(graph) ?? [{ path: `${stem}.${emitter.ext}`, content: emitter.emit(graph) }]
}

/* ------------------------------------------------------------------ *
 * Shared helpers
 * ------------------------------------------------------------------ */

/** Escape text going into an XML/SVG text node. */
const xmlText = (text: string): string =>
  text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

/**
 * Make user text safe inside a comment.
 *
 * The palette title and a swatch's name are free text, and a title carrying a
 * comment terminator closes a CSS block comment early — corrupting every rule
 * after it. A newline does the same to the line comments the JavaScript
 * emitters use.
 */
const safeComment = (text: string): string =>
  text
    .replace(/\*\/|\/\*/g, ' ')
    .replace(/[\r\n]+/g, ' ')
    .trim()

/**
 * The name Tailwind should see.
 *
 * Tailwind reads utilities off `--color-*`, so this file is kebab whatever the
 * configured case is — but the user's prefix and suffix still belong in it.
 * Stripping a hard-coded `color-` off the *rendered* name only worked in
 * kebab: with camelCase the name was `colorBrand`, the strip missed, and every
 * variable came out as `--color-colorBrand`.
 */
function tailwindName(token: Token, config: ExportConfig): string {
  return composeName({ ...config, case: 'kebab' }, token.id).replace(/^color-/, '')
}

function value(color: Oklch, config: ExportConfig): string {
  return formatColor(color, config.format, config.precision)
}

function header(graph: TokenGraph, comment: (text: string) => string): string {
  if (!graph.config.includeComments) return ''
  const lines = [
    `${safeComment(graph.title)} — generated by DevColorz`,
    `${graph.tokens.length} tokens${graph.hasDark ? ', light and dark' : ''}, ${graph.config.format} notation`,
  ]
  return lines.map(comment).join('\n') + '\n\n'
}

/**
 * The note that follows a declaration.
 *
 * Two independent switches, so both are checked. Turning Comments off used to
 * drop the header and leave the per-token provenance note on every line — in a
 * palette with scales, a hundred-odd comments in a file the user had just
 * asked to have none.
 */
function contrastNote(token: Token, config: ExportConfig): string {
  const note = config.includeComments && token.comment ? safeComment(token.comment) : ''
  if (!config.includeContrast) return note ? ` /* ${note} */` : ''
  const level = wcagLevel(token.meta.contrastOnWhite)
  const parts = [
    note,
    `on white ${token.meta.contrastOnWhite.toFixed(2)}:1 (${level}), Lc ${token.meta.apcaOnWhite.toFixed(0)}`,
  ].filter(Boolean)
  return ` /* ${parts.join(' · ')} */`
}

/**
 * The selector for a mode override.
 *
 * `.dark` on its own only outranks the base rule when that rule is a single
 * class or pseudo-class — `:root`, the default. Against `#app` or `.theme` it
 * loses on specificity whatever the source order, and the whole override is
 * dead CSS. For any other base selector the mode class is paired with it, on
 * the same element and as an ancestor: `.dark#app, .dark #app` outranks
 * `#app` wherever a toggle script is likely to put the class.
 */
function modeSelector(config: ExportConfig, modeClass: string): string {
  const base = config.selector.trim()
  if (/^(:root|html|body)$/i.test(base)) return modeClass
  // Only a class, id, attribute or pseudo-class can follow another selector
  // without a space; `html.theme` would otherwise become `.darkhtml.theme`.
  const compound = /^[.#[:]/.test(base) ? `${modeClass}${base}, ` : ''
  return `${compound}${modeClass} ${base}`
}

/** Emit the tokens of one mode as CSS declarations. */
function declarations(graph: TokenGraph, mode: 'light' | 'dark', indent = '  '): string {
  const lines: string[] = []
  for (const token of graph.tokens) {
    const color = mode === 'light' ? token.light : token.dark
    if (!color) continue
    lines.push(`${indent}--${token.name}: ${value(color, graph.config)};${
      mode === 'light' ? contrastNote(token, graph.config) : ''
    }`)
  }
  return lines.join('\n')
}

/* ------------------------------------------------------------------ *
 * CSS
 * ------------------------------------------------------------------ */

export const cssEmitter: Emitter = {
  id: 'css',
  label: 'CSS custom properties',
  ext: 'css',
  language: 'css',
  hint: 'Plain custom properties on a selector of your choice. Works everywhere, in any framework or none.',
  emit(graph) {
    const { config } = graph
    let out = header(graph, (t) => `/* ${t} */`)
    out += `${config.selector} {\n${declarations(graph, 'light')}\n}\n`

    if (graph.hasDark) {
      const dark = declarations(graph, 'dark')
      const delivery = config.darkDelivery
      if (delivery === 'media' || delivery === 'both') {
        out += `\n@media (prefers-color-scheme: dark) {\n  ${config.selector} {\n${declarations(graph, 'dark', '    ')}\n  }\n}\n`
      }
      if (delivery === 'class' || delivery === 'both') {
        out += `\n${modeSelector(config, config.darkClass)} {\n${dark}\n}\n`
      }
      if (delivery === 'attribute') {
        out += `\n${modeSelector(config, config.darkAttribute)} {\n${dark}\n}\n`
      }
      if (delivery === 'both') {
        /*
         * The light override belongs *inside* the media query, and nowhere
         * else.
         *
         * A media query adds no specificity, so the dark rule above is a plain
         * `:root` at (0,1,0). The obvious light override — `:root:not(.dark)` —
         * is (0,2,0) and sits outside any media query, so it matched every
         * visitor who had not yet run a toggle script and beat the dark rule
         * unconditionally: the whole `@media` block was dead CSS and a dark-OS
         * visitor got the light palette, which is the exact flash this delivery
         * exists to prevent. Hard-coding `.dark` there made it worse — rename
         * the dark class and `:not(.dark)` matched even with the toggle applied,
         * so dark mode never rendered at all.
         *
         * Emitted last so that, at equal specificity, source order decides:
         * dark OS with no class wins on the media `:root`; dark OS with the
         * light class wins here; light OS with the dark class wins above.
         */
        out += `\n@media (prefers-color-scheme: dark) {\n  ${modeSelector(config, config.lightClass)} {\n${declarations(graph, 'light', '    ')}\n  }\n}\n`
      }
    }
    return out
  },
}

/* ------------------------------------------------------------------ *
 * Tailwind
 * ------------------------------------------------------------------ */

export const tailwind4Emitter: Emitter = {
  id: 'tailwind4',
  label: 'Tailwind CSS v4',
  ext: 'css',
  language: 'css',
  hint: 'A `@theme` block. Tailwind v4 reads its palette from CSS, so this is all it takes to get `bg-brand-500` and friends.',
  emit(graph) {
    const { config } = graph
    let out = header(graph, (t) => `/* ${t} */`)
    out += '@import "tailwindcss";\n\n'
    // Tailwind only generates utilities for variables under its own namespaces,
    // so the prefix has to be `--color-` regardless of what the user picked.
    out += '@theme {\n'
    for (const token of graph.tokens) {
      out += `  --color-${tailwindName(token, config)}: ${value(token.light, config)};\n`
    }
    out += '}\n'

    if (graph.hasDark) {
      // The variant names the same class the values below are keyed on. A
      // literal `.dark` here left `dark:` utilities looking for a class the
      // user's own toggle never sets, once the class had been renamed.
      out += `\n@custom-variant dark (&:where(${config.darkClass}, ${config.darkClass} *));\n`
      out += `\n${config.darkClass} {\n`
      for (const token of graph.tokens) {
        if (!token.dark) continue
        out += `  --color-${tailwindName(token, config)}: ${value(token.dark, config)};\n`
      }
      out += '}\n'
    }
    return out
  },
}

export const tailwind3Emitter: Emitter = {
  id: 'tailwind3',
  label: 'Tailwind CSS v3 config',
  ext: 'js',
  language: 'javascript',
  hint: 'A `theme.extend.colors` object for `tailwind.config.js`. Keys are always kebab-case, because that is what the utility name is built from.',
  emit(graph) {
    const { config } = graph
    // Group `brand-500` under `brand: { 500: … }` so the utilities read the way
    // Tailwind users expect.
    const tree: Record<string, string | Record<string, string>> = {}
    for (const token of graph.tokens) {
      // `token.id` is already the un-prefixed, un-suffixed, collision-free
      // kebab stem, which is the shape a Tailwind config wants whatever the
      // configured case is. Building a RegExp out of the raw prefix instead
      // threw outright on a prefix containing a regex metacharacter, and
      // matched nothing at all in any case but kebab.
      const name = token.id
      const cut = token.kind === 'base' ? -1 : name.lastIndexOf('-')
      if (cut > 0) {
        const stem = name.slice(0, cut)
        const step = name.slice(cut + 1)
        // The bare colour may already be sitting on this key — `brand` before
        // `brand-500`. Tailwind's own convention for a bucket that also has a
        // value of its own is `DEFAULT`; assigning a step onto the string
        // threw instead, which broke the emitter for the nesting it exists for.
        const existing = tree[stem]
        const bucket = (typeof existing === 'string'
          ? (tree[stem] = { DEFAULT: existing })
          : (tree[stem] ??= {})) as Record<string, string>
        bucket[step] = value(token.light, config)
      } else {
        tree[name] = value(token.light, config)
      }
    }
    const body = JSON.stringify(tree, null, 2)
      .split('\n')
      .map((line, i) => (i === 0 ? line : `      ${line}`))
      .join('\n')
    return `${header(graph, (t) => `// ${t}`)}/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: ${body},
    },
  },
}
`
  },
}

/* ------------------------------------------------------------------ *
 * Preprocessors
 * ------------------------------------------------------------------ */

export const scssEmitter: Emitter = {
  id: 'scss',
  label: 'SCSS variables + map',
  ext: 'scss',
  language: 'scss',
  hint: 'Individual `$variables` plus a `$palette` map you can iterate with `@each`.',
  emit(graph) {
    const { config } = graph
    let out = header(graph, (t) => `// ${t}`)
    for (const token of graph.tokens) {
      out += `$${token.name}: ${value(token.light, config)};\n`
    }
    out += `\n$palette: (\n`
    out += graph.tokens.map((t) => `  '${t.name}': $${t.name},`).join('\n')
    out += `\n);\n`
    if (graph.hasDark) {
      out += `\n$palette-dark: (\n`
      out += graph.tokens
        .filter((t) => t.dark)
        .map((t) => `  '${t.name}': ${value(t.dark!, config)},`)
        .join('\n')
      out += `\n);\n`
    }
    return out
  },
}

export const lessEmitter: Emitter = {
  id: 'less',
  label: 'Less variables',
  ext: 'less',
  language: 'less',
  hint: 'One `@variable` per token.',
  emit(graph) {
    const { config } = graph
    return (
      header(graph, (t) => `// ${t}`) +
      graph.tokens.map((t) => `@${t.name}: ${value(t.light, config)};`).join('\n') +
      '\n'
    )
  },
}

/* ------------------------------------------------------------------ *
 * Data
 * ------------------------------------------------------------------ */

export const jsonEmitter: Emitter = {
  id: 'json',
  label: 'JSON',
  ext: 'json',
  language: 'json',
  hint: 'A flat object of name → value, with a `dark` block when dark variants are on.',
  emit(graph) {
    const { config } = graph
    const light: Record<string, string> = {}
    const dark: Record<string, string> = {}
    for (const token of graph.tokens) {
      light[token.name] = value(token.light, config)
      if (token.dark) dark[token.name] = value(token.dark, config)
    }
    return JSON.stringify(
      graph.hasDark ? { name: graph.title, light, dark } : { name: graph.title, ...light },
      null,
      2,
    ) + '\n'
  },
}

export const dtcgEmitter: Emitter = {
  id: 'dtcg',
  label: 'Design Tokens (DTCG)',
  ext: 'tokens.json',
  language: 'json',
  hint: 'The W3C Design Tokens Community Group format, consumed by Style Dictionary, Tokens Studio and most token pipelines.',
  emit(graph) {
    const build = (mode: 'light' | 'dark') => {
      const group: Record<string, unknown> = {}
      for (const token of graph.tokens) {
        const color = mode === 'light' ? token.light : token.dark
        if (!color) continue
        const rgb = toRgb(color)
        group[token.name] = {
          $type: 'color',
          $value: {
            colorSpace: 'oklch',
            components: [
              Number((color.l ?? 0).toFixed(5)),
              Number((color.c ?? 0).toFixed(5)),
              Number((color.h ?? 0).toFixed(3)),
            ],
            alpha: color.alpha ?? 1,
            hex: `#${hexToken(rgb).toLowerCase()}`,
          },
          ...(token.comment ? { $description: token.comment } : {}),
          $extensions: {
            'org.devcolorz': {
              contrastOnWhite: Number(token.meta.contrastOnWhite.toFixed(3)),
              apcaOnWhite: Number(token.meta.apcaOnWhite.toFixed(1)),
              kind: token.kind,
            },
          },
        }
      }
      return group
    }
    const doc: Record<string, unknown> = {
      $description: `${graph.title} — generated by DevColorz`,
      color: build('light'),
    }
    if (graph.hasDark) doc.colorDark = build('dark')
    return JSON.stringify(doc, null, 2) + '\n'
  },
}

export const tsEmitter: Emitter = {
  id: 'ts',
  label: 'TypeScript',
  ext: 'ts',
  language: 'typescript',
  hint: 'A `const` object with a literal type, so consumers get autocomplete on token names.',
  emit(graph) {
    const { config } = graph
    const entries = graph.tokens
      .map((t) => `  '${t.name}': '${value(t.light, config)}',`)
      .join('\n')
    let out = header(graph, (t) => `// ${t}`)
    out += `export const palette = {\n${entries}\n} as const\n\n`
    out += `export type PaletteToken = keyof typeof palette\n`
    if (graph.hasDark) {
      const darkEntries = graph.tokens
        .filter((t) => t.dark)
        .map((t) => `  '${t.name}': '${value(t.dark!, config)}',`)
        .join('\n')
      out += `\nexport const paletteDark = {\n${darkEntries}\n} as const satisfies Partial<Record<PaletteToken, string>>\n`
    }
    return out
  },
}

export const csvEmitter: Emitter = {
  id: 'csv',
  label: 'CSV',
  ext: 'csv',
  language: 'plaintext',
  hint: 'One row per token, with hex, OKLCH channels and both contrast metrics — handy for a spreadsheet audit.',
  emit(graph) {
    const rows = [
      'name,kind,hex,oklch,l,c,h,contrast_on_white,contrast_on_black,apca_on_white,apca_on_black,wcag_level_on_white',
    ]
    for (const token of graph.tokens) {
      const c = token.light
      rows.push(
        [
          token.name,
          token.kind,
          formatColor(c, 'hex'),
          formatColor(c, 'oklch'),
          (c.l ?? 0).toFixed(4),
          (c.c ?? 0).toFixed(4),
          (c.h ?? 0).toFixed(2),
          token.meta.contrastOnWhite.toFixed(3),
          token.meta.contrastOnBlack.toFixed(3),
          token.meta.apcaOnWhite.toFixed(1),
          token.meta.apcaOnBlack.toFixed(1),
          wcagLevel(token.meta.contrastOnWhite),
        ].join(','),
      )
    }
    return rows.join('\n') + '\n'
  },
}

/* ------------------------------------------------------------------ *
 * Design tools
 * ------------------------------------------------------------------ */

export const gplEmitter: Emitter = {
  id: 'gpl',
  label: 'GIMP palette',
  ext: 'gpl',
  language: 'plaintext',
  hint: 'Opens in GIMP, Inkscape, Krita and Aseprite.',
  emit(graph) {
    let out = `GIMP Palette\nName: ${graph.title}\nColumns: ${Math.min(16, graph.tokens.length)}\n#\n`
    for (const token of graph.tokens) {
      const rgb = toRgb(token.light)
      const to255 = (v: number) => String(Math.round(Math.min(1, Math.max(0, v)) * 255)).padStart(3, ' ')
      out += `${to255(rgb.r)} ${to255(rgb.g)} ${to255(rgb.b)}\t${token.name}\n`
    }
    return out
  },
}

export const svgEmitter: Emitter = {
  id: 'svg',
  label: 'SVG swatch sheet',
  ext: 'svg',
  language: 'xml',
  hint: 'A vector contact sheet with hex labels — drop it into Figma or a slide deck.',
  emit(graph) {
    const tokens = graph.tokens.filter((t) => t.kind === 'base')
    const list = tokens.length ? tokens : graph.tokens
    const w = 160
    const h = 200
    // At least one cell: with every colour excluded the grid used to be zero
    // columns wide and its row count NaN, which no viewer opens.
    const columns = Math.max(1, Math.min(6, list.length))
    const rows = Math.max(1, Math.ceil(list.length / columns))
    let out = `<svg xmlns="http://www.w3.org/2000/svg" width="${columns * w}" height="${rows * h}" viewBox="0 0 ${columns * w} ${rows * h}" font-family="ui-sans-serif, system-ui, sans-serif">\n`
    out += `  <title>${xmlText(graph.title)}</title>\n`
    list.forEach((token, index) => {
      const x = (index % columns) * w
      const y = Math.floor(index / columns) * h
      const hex = formatColor(token.light, 'hex')
      // `apcaOnWhite` is high for a *dark* swatch, so the old test picked
      // near-black ink for near-black tiles and white for pale ones — every
      // label on the sheet was invisible. The engine already answers this.
      const ink = (bestBlackOrWhite(token.light).l ?? 0) > 0.5 ? '#ffffff' : '#111111'
      out += `  <g transform="translate(${x} ${y})">\n`
      out += `    <rect width="${w}" height="${h}" fill="${hex}"/>\n`
      out += `    <text x="16" y="${h - 34}" font-size="15" font-weight="600" fill="${ink}" font-family="ui-monospace, monospace">${hex.toUpperCase()}</text>\n`
      out += `    <text x="16" y="${h - 16}" font-size="11" fill="${ink}" opacity="0.75">${xmlText(token.name)}</text>\n`
      out += `  </g>\n`
    })
    out += '</svg>\n'
    return out
  },
}

/* ------------------------------------------------------------------ *
 * Platforms
 * ------------------------------------------------------------------ */

/** One Android resources document for one mode. */
function androidResources(graph: TokenGraph, mode: 'light' | 'dark'): string {
  const name = (t: Token) => t.name.replace(/-/g, '_')
  const argb = (color: Oklch) => {
    const rgb = toRgb(color)
    const a = Math.round((color.alpha ?? 1) * 255)
    const hex = hexToken(rgb)
    return `#${a === 255 ? '' : a.toString(16).padStart(2, '0').toUpperCase()}${hex}`
  }
  let out = '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
  for (const token of graph.tokens) {
    const color = mode === 'light' ? token.light : token.dark
    if (!color) continue
    out += `    <color name="${name(token)}">${argb(color)}</color>\n`
  }
  return out + '</resources>\n'
}

export const androidEmitter: Emitter = {
  id: 'android',
  label: 'Android colors.xml',
  ext: 'xml',
  language: 'xml',
  hint: 'Drop into `res/values/`. Dark values belong in `res/values-night/colors.xml`, and the download gives you both files.',
  emit(graph) {
    // Both documents on screen, each headed with where it goes. They are two
    // files rather than one: an XML document has one root, and the download
    // splits them accordingly.
    let out = `<!-- res/values/colors.xml -->\n${androidResources(graph, 'light')}`
    if (graph.hasDark) {
      out += `\n<!-- res/values-night/colors.xml -->\n${androidResources(graph, 'dark')}`
    }
    return out
  },
  files(graph) {
    const files: EmittedFile[] = [
      { path: 'values/colors.xml', content: androidResources(graph, 'light') },
    ]
    if (graph.hasDark) {
      files.push({ path: 'values-night/colors.xml', content: androidResources(graph, 'dark') })
    }
    return files
  },
}

export const swiftEmitter: Emitter = {
  id: 'swift',
  label: 'SwiftUI',
  ext: 'swift',
  language: 'swift',
  hint: 'A `Color` extension. Uses the Display P3 initializer so wide-gamut colors survive on Apple hardware.',
  emit(graph) {
    const camel = (name: string) =>
      name
        .split('-')
        .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
        .join('')
    let out = header(graph, (t) => `// ${t}`)
    out += 'import SwiftUI\n\npublic extension Color {\n'
    for (const token of graph.tokens) {
      const rgb = toRgb(token.light)
      const f = (v: number) => Math.min(1, Math.max(0, v)).toFixed(4)
      out += `    static let ${camel(token.name)} = Color(.displayP3, red: ${f(rgb.r)}, green: ${f(rgb.g)}, blue: ${f(rgb.b)}, opacity: ${(token.light.alpha ?? 1).toFixed(3)})\n`
    }
    out += '}\n'
    return out
  },
}

export const flutterEmitter: Emitter = {
  id: 'flutter',
  label: 'Flutter / Dart',
  ext: 'dart',
  language: 'dart',
  hint: 'A class of `Color` constants in ARGB form.',
  emit(graph) {
    const camel = (name: string) =>
      name
        .split('-')
        .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
        .join('')
    let out = header(graph, (t) => `// ${t}`)
    out += "import 'package:flutter/material.dart';\n\nclass PaletteColors {\n  PaletteColors._();\n\n"
    for (const token of graph.tokens) {
      const a = Math.round((token.light.alpha ?? 1) * 255)
        .toString(16)
        .padStart(2, '0')
      out += `  static const Color ${camel(token.name)} = Color(0x${a.toUpperCase()}${hexToken(token.light)});\n`
    }
    out += '}\n'
    return out
  },
}

export const composeEmitter: Emitter = {
  id: 'compose',
  label: 'Jetpack Compose',
  ext: 'kt',
  language: 'kotlin',
  hint: 'Kotlin `val`s of `Color`, ready for a Material theme.',
  emit(graph) {
    const pascal = (name: string) =>
      name
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('')
    let out = header(graph, (t) => `// ${t}`)
    out += 'import androidx.compose.ui.graphics.Color\n\n'
    for (const token of graph.tokens) {
      const a = Math.round((token.light.alpha ?? 1) * 255)
        .toString(16)
        .padStart(2, '0')
      out += `val ${pascal(token.name)} = Color(0x${a.toUpperCase()}${hexToken(token.light)})\n`
    }
    return out
  },
}

/* ------------------------------------------------------------------ *
 * Registry
 * ------------------------------------------------------------------ */

export const shadcnRegistryEmitter: Emitter = {
  id: 'registry',
  label: 'shadcn registry item',
  ext: 'json',
  language: 'json',
  hint: 'A registry item you can host and install with `npx shadcn add <url>`.',
  emit(graph) {
    const { config } = graph
    const light: Record<string, string> = {}
    const dark: Record<string, string> = {}
    for (const token of graph.tokens) {
      light[token.name] = value(token.light, config)
      if (token.dark) dark[token.name] = value(token.dark, config)
    }
    return (
      JSON.stringify(
        {
          $schema: 'https://ui.shadcn.com/schema/registry-item.json',
          name: (graph.title || 'palette').toLowerCase().replace(/\W+/g, '-'),
          type: 'registry:theme',
          cssVars: graph.hasDark ? { theme: {}, light, dark } : { theme: {}, light },
        },
        null,
        2,
      ) + '\n'
    )
  },
}

export const EMITTERS: Emitter[] = [
  cssEmitter,
  tailwind4Emitter,
  tailwind3Emitter,
  scssEmitter,
  lessEmitter,
  jsonEmitter,
  dtcgEmitter,
  tsEmitter,
  csvEmitter,
  svgEmitter,
  gplEmitter,
  androidEmitter,
  swiftEmitter,
  flutterEmitter,
  composeEmitter,
  shadcnRegistryEmitter,
]

export const EMITTERS_BY_ID: Record<string, Emitter> = Object.fromEntries(
  EMITTERS.map((e) => [e.id, e]),
)
