/**
 * Output formats.
 *
 * Every emitter takes the same `TokenGraph` and returns text, so adding a
 * format cannot change which tokens exist — only how they are written down.
 */

import { formatColor, hexToken, toRgb } from '@/lib/color/convert'
import { wcagLevel } from '@/lib/color/contrast'
import type { Oklch } from '@/lib/color/types'
import type { ExportConfig } from './config'
import type { Token, TokenGraph } from './graph'

export interface Emitter {
  id: string
  label: string
  /** File extension, without the dot. */
  ext: string
  language: string
  /** One line explaining when to reach for this format. */
  hint: string
  emit(graph: TokenGraph): string
}

/* ------------------------------------------------------------------ *
 * Shared helpers
 * ------------------------------------------------------------------ */

function value(color: Oklch, config: ExportConfig): string {
  return formatColor(color, config.format, config.precision)
}

function header(graph: TokenGraph, comment: (text: string) => string): string {
  if (!graph.config.includeComments) return ''
  const lines = [
    `${graph.title} — generated by DevColorz`,
    `${graph.tokens.length} tokens${graph.hasDark ? ', light and dark' : ''}, ${graph.config.format} notation`,
  ]
  return lines.map(comment).join('\n') + '\n\n'
}

function contrastNote(token: Token, config: ExportConfig): string {
  if (!config.includeContrast) return token.comment ? ` /* ${token.comment} */` : ''
  const level = wcagLevel(token.meta.contrastOnWhite)
  const parts = [
    token.comment,
    `on white ${token.meta.contrastOnWhite.toFixed(2)}:1 (${level}), Lc ${token.meta.apcaOnWhite.toFixed(0)}`,
  ].filter(Boolean)
  return ` /* ${parts.join(' · ')} */`
}

/** Emit the tokens of one mode as CSS declarations. */
function declarations(graph: TokenGraph, mode: 'light' | 'dark', indent = '  '): string {
  const lines: string[] = []
  for (const token of graph.tokens) {
    const color = mode === 'light' ? token.light : token.dark
    if (!color) continue
    lines.push(`${indent}--${token.name}: ${value(color, graph.config)};${
      mode === 'light' ? contrastNote(token, graph.config) : ''
    }`)
  }
  return lines.join('\n')
}

/* ------------------------------------------------------------------ *
 * CSS
 * ------------------------------------------------------------------ */

export const cssEmitter: Emitter = {
  id: 'css',
  label: 'CSS custom properties',
  ext: 'css',
  language: 'css',
  hint: 'Plain custom properties on a selector of your choice. Works everywhere, in any framework or none.',
  emit(graph) {
    const { config } = graph
    let out = header(graph, (t) => `/* ${t} */`)
    out += `${config.selector} {\n${declarations(graph, 'light')}\n}\n`

    if (graph.hasDark) {
      const dark = declarations(graph, 'dark')
      const delivery = config.darkDelivery
      if (delivery === 'media' || delivery === 'both') {
        out += `\n@media (prefers-color-scheme: dark) {\n  ${config.selector} {\n${declarations(graph, 'dark', '    ')}\n  }\n}\n`
      }
      if (delivery === 'class' || delivery === 'both') {
        out += `\n${config.darkClass} {\n${dark}\n}\n`
      }
      if (delivery === 'attribute') {
        out += `\n${config.darkAttribute} {\n${dark}\n}\n`
      }
      if (delivery === 'both') {
        // The light override is what makes an in-page toggle work in both
        // directions: without it, a user on a dark OS cannot choose light.
        out += `\n:root:not(.dark), .light {\n${declarations(graph, 'light')}\n}\n`
      }
    }
    return out
  },
}

/* ------------------------------------------------------------------ *
 * Tailwind
 * ------------------------------------------------------------------ */

export const tailwind4Emitter: Emitter = {
  id: 'tailwind4',
  label: 'Tailwind CSS v4',
  ext: 'css',
  language: 'css',
  hint: 'A `@theme` block. Tailwind v4 reads its palette from CSS, so this is all it takes to get `bg-brand-500` and friends.',
  emit(graph) {
    const { config } = graph
    let out = header(graph, (t) => `/* ${t} */`)
    out += '@import "tailwindcss";\n\n'
    // Tailwind only generates utilities for variables under its own namespaces,
    // so the prefix has to be `--color-` regardless of what the user picked.
    out += '@theme {\n'
    for (const token of graph.tokens) {
      const name = token.name.replace(/^color-/, '')
      out += `  --color-${name}: ${value(token.light, config)};\n`
    }
    out += '}\n'

    if (graph.hasDark) {
      out += '\n@custom-variant dark (&:is(.dark *));\n'
      out += `\n${config.darkClass} {\n`
      for (const token of graph.tokens) {
        if (!token.dark) continue
        const name = token.name.replace(/^color-/, '')
        out += `  --color-${name}: ${value(token.dark, config)};\n`
      }
      out += '}\n'
    }
    return out
  },
}

export const tailwind3Emitter: Emitter = {
  id: 'tailwind3',
  label: 'Tailwind CSS v3 config',
  ext: 'js',
  language: 'javascript',
  hint: 'A `theme.extend.colors` object for `tailwind.config.js`.',
  emit(graph) {
    const { config } = graph
    // Group `brand-500` under `brand: { 500: … }` so the utilities read the way
    // Tailwind users expect.
    const tree: Record<string, string | Record<string, string>> = {}
    for (const token of graph.tokens) {
      const name = token.name.replace(new RegExp(`^${config.prefix}-?`), '')
      const match = /^(.*)-(\d{1,3}|a\d{1,3})$/.exec(name)
      if (match) {
        const [, stem, step] = match
        const bucket = (tree[stem] ??= {}) as Record<string, string>
        bucket[step] = value(token.light, config)
      } else {
        tree[name] = value(token.light, config)
      }
    }
    const body = JSON.stringify(tree, null, 2)
      .split('\n')
      .map((line, i) => (i === 0 ? line : `      ${line}`))
      .join('\n')
    return `${header(graph, (t) => `// ${t}`)}/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: ${body},
    },
  },
}
`
  },
}

/* ------------------------------------------------------------------ *
 * Preprocessors
 * ------------------------------------------------------------------ */

export const scssEmitter: Emitter = {
  id: 'scss',
  label: 'SCSS variables + map',
  ext: 'scss',
  language: 'scss',
  hint: 'Individual `$variables` plus a `$palette` map you can iterate with `@each`.',
  emit(graph) {
    const { config } = graph
    let out = header(graph, (t) => `// ${t}`)
    for (const token of graph.tokens) {
      out += `$${token.name}: ${value(token.light, config)};\n`
    }
    out += `\n$palette: (\n`
    out += graph.tokens.map((t) => `  '${t.name}': $${t.name},`).join('\n')
    out += `\n);\n`
    if (graph.hasDark) {
      out += `\n$palette-dark: (\n`
      out += graph.tokens
        .filter((t) => t.dark)
        .map((t) => `  '${t.name}': ${value(t.dark!, config)},`)
        .join('\n')
      out += `\n);\n`
    }
    return out
  },
}

export const lessEmitter: Emitter = {
  id: 'less',
  label: 'Less variables',
  ext: 'less',
  language: 'less',
  hint: 'One `@variable` per token.',
  emit(graph) {
    const { config } = graph
    return (
      header(graph, (t) => `// ${t}`) +
      graph.tokens.map((t) => `@${t.name}: ${value(t.light, config)};`).join('\n') +
      '\n'
    )
  },
}

/* ------------------------------------------------------------------ *
 * Data
 * ------------------------------------------------------------------ */

export const jsonEmitter: Emitter = {
  id: 'json',
  label: 'JSON',
  ext: 'json',
  language: 'json',
  hint: 'A flat object of name → value, with a `dark` block when dark variants are on.',
  emit(graph) {
    const { config } = graph
    const light: Record<string, string> = {}
    const dark: Record<string, string> = {}
    for (const token of graph.tokens) {
      light[token.name] = value(token.light, config)
      if (token.dark) dark[token.name] = value(token.dark, config)
    }
    return JSON.stringify(
      graph.hasDark ? { name: graph.title, light, dark } : { name: graph.title, ...light },
      null,
      2,
    ) + '\n'
  },
}

export const dtcgEmitter: Emitter = {
  id: 'dtcg',
  label: 'Design Tokens (DTCG)',
  ext: 'tokens.json',
  language: 'json',
  hint: 'The W3C Design Tokens Community Group format, consumed by Style Dictionary, Tokens Studio and most token pipelines.',
  emit(graph) {
    const { config } = graph
    const build = (mode: 'light' | 'dark') => {
      const group: Record<string, unknown> = {}
      for (const token of graph.tokens) {
        const color = mode === 'light' ? token.light : token.dark
        if (!color) continue
        const rgb = toRgb(color)
        group[token.name] = {
          $type: 'color',
          $value: {
            colorSpace: 'oklch',
            components: [
              Number((color.l ?? 0).toFixed(5)),
              Number((color.c ?? 0).toFixed(5)),
              Number((color.h ?? 0).toFixed(3)),
            ],
            alpha: color.alpha ?? 1,
            hex: `#${hexToken(rgb).toLowerCase()}`,
          },
          ...(token.comment ? { $description: token.comment } : {}),
          $extensions: {
            'vision.fabula.devcolorz': {
              contrastOnWhite: Number(token.meta.contrastOnWhite.toFixed(3)),
              apcaOnWhite: Number(token.meta.apcaOnWhite.toFixed(1)),
              kind: token.kind,
            },
          },
        }
      }
      return group
    }
    const doc: Record<string, unknown> = {
      $description: `${graph.title} — generated by DevColorz`,
      color: build('light'),
    }
    if (graph.hasDark) doc.colorDark = build('dark')
    return JSON.stringify(doc, null, 2) + '\n'
  },
}

export const tsEmitter: Emitter = {
  id: 'ts',
  label: 'TypeScript',
  ext: 'ts',
  language: 'typescript',
  hint: 'A `const` object with a literal type, so consumers get autocomplete on token names.',
  emit(graph) {
    const { config } = graph
    const entries = graph.tokens
      .map((t) => `  '${t.name}': '${value(t.light, config)}',`)
      .join('\n')
    let out = header(graph, (t) => `// ${t}`)
    out += `export const palette = {\n${entries}\n} as const\n\n`
    out += `export type PaletteToken = keyof typeof palette\n`
    if (graph.hasDark) {
      const darkEntries = graph.tokens
        .filter((t) => t.dark)
        .map((t) => `  '${t.name}': '${value(t.dark!, config)}',`)
        .join('\n')
      out += `\nexport const paletteDark = {\n${darkEntries}\n} as const satisfies Partial<Record<PaletteToken, string>>\n`
    }
    return out
  },
}

export const csvEmitter: Emitter = {
  id: 'csv',
  label: 'CSV',
  ext: 'csv',
  language: 'plaintext',
  hint: 'One row per token, with hex, OKLCH channels and both contrast metrics — handy for a spreadsheet audit.',
  emit(graph) {
    const rows = [
      'name,kind,hex,oklch,l,c,h,contrast_on_white,contrast_on_black,apca_on_white,apca_on_black,wcag_level_on_white',
    ]
    for (const token of graph.tokens) {
      const c = token.light
      rows.push(
        [
          token.name,
          token.kind,
          formatColor(c, 'hex'),
          formatColor(c, 'oklch'),
          (c.l ?? 0).toFixed(4),
          (c.c ?? 0).toFixed(4),
          (c.h ?? 0).toFixed(2),
          token.meta.contrastOnWhite.toFixed(3),
          token.meta.contrastOnBlack.toFixed(3),
          token.meta.apcaOnWhite.toFixed(1),
          token.meta.apcaOnBlack.toFixed(1),
          wcagLevel(token.meta.contrastOnWhite),
        ].join(','),
      )
    }
    return rows.join('\n') + '\n'
  },
}

/* ------------------------------------------------------------------ *
 * Design tools
 * ------------------------------------------------------------------ */

export const gplEmitter: Emitter = {
  id: 'gpl',
  label: 'GIMP palette',
  ext: 'gpl',
  language: 'plaintext',
  hint: 'Opens in GIMP, Inkscape, Krita and Aseprite.',
  emit(graph) {
    let out = `GIMP Palette\nName: ${graph.title}\nColumns: ${Math.min(16, graph.tokens.length)}\n#\n`
    for (const token of graph.tokens) {
      const rgb = toRgb(token.light)
      const to255 = (v: number) => String(Math.round(Math.min(1, Math.max(0, v)) * 255)).padStart(3, ' ')
      out += `${to255(rgb.r)} ${to255(rgb.g)} ${to255(rgb.b)}\t${token.name}\n`
    }
    return out
  },
}

export const svgEmitter: Emitter = {
  id: 'svg',
  label: 'SVG swatch sheet',
  ext: 'svg',
  language: 'xml',
  hint: 'A vector contact sheet with hex labels — drop it into Figma or a slide deck.',
  emit(graph) {
    const tokens = graph.tokens.filter((t) => t.kind === 'base')
    const list = tokens.length ? tokens : graph.tokens
    const w = 160
    const h = 200
    const columns = Math.min(6, list.length)
    const rows = Math.ceil(list.length / columns)
    let out = `<svg xmlns="http://www.w3.org/2000/svg" width="${columns * w}" height="${rows * h}" viewBox="0 0 ${columns * w} ${rows * h}" font-family="ui-sans-serif, system-ui, sans-serif">\n`
    out += `  <title>${graph.title}</title>\n`
    list.forEach((token, index) => {
      const x = (index % columns) * w
      const y = Math.floor(index / columns) * h
      const hex = formatColor(token.light, 'hex')
      const ink = token.meta.apcaOnWhite > 45 ? '#111111' : '#ffffff'
      out += `  <g transform="translate(${x} ${y})">\n`
      out += `    <rect width="${w}" height="${h}" fill="${hex}"/>\n`
      out += `    <text x="16" y="${h - 34}" font-size="15" font-weight="600" fill="${ink}" font-family="ui-monospace, monospace">${hex.toUpperCase()}</text>\n`
      out += `    <text x="16" y="${h - 16}" font-size="11" fill="${ink}" opacity="0.75">${token.name}</text>\n`
      out += `  </g>\n`
    })
    out += '</svg>\n'
    return out
  },
}

/* ------------------------------------------------------------------ *
 * Platforms
 * ------------------------------------------------------------------ */

export const androidEmitter: Emitter = {
  id: 'android',
  label: 'Android colors.xml',
  ext: 'xml',
  language: 'xml',
  hint: 'Drop into `res/values/`. Dark values belong in `res/values-night/colors.xml`.',
  emit(graph) {
    const name = (t: Token) => t.name.replace(/-/g, '_')
    const argb = (color: Oklch) => {
      const rgb = toRgb(color)
      const a = Math.round((color.alpha ?? 1) * 255)
      const hex = hexToken(rgb)
      return `#${a === 255 ? '' : a.toString(16).padStart(2, '0').toUpperCase()}${hex}`
    }
    let out = '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
    for (const token of graph.tokens) {
      out += `    <color name="${name(token)}">${argb(token.light)}</color>\n`
    }
    out += '</resources>\n'
    if (graph.hasDark) {
      out += '\n<!-- res/values-night/colors.xml -->\n<resources>\n'
      for (const token of graph.tokens) {
        if (!token.dark) continue
        out += `    <color name="${name(token)}">${argb(token.dark)}</color>\n`
      }
      out += '</resources>\n'
    }
    return out
  },
}

export const swiftEmitter: Emitter = {
  id: 'swift',
  label: 'SwiftUI',
  ext: 'swift',
  language: 'swift',
  hint: 'A `Color` extension. Uses the Display P3 initialiser so wide-gamut colours survive on Apple hardware.',
  emit(graph) {
    const camel = (name: string) =>
      name
        .split('-')
        .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
        .join('')
    let out = header(graph, (t) => `// ${t}`)
    out += 'import SwiftUI\n\npublic extension Color {\n'
    for (const token of graph.tokens) {
      const rgb = toRgb(token.light)
      const f = (v: number) => Math.min(1, Math.max(0, v)).toFixed(4)
      out += `    static let ${camel(token.name)} = Color(.displayP3, red: ${f(rgb.r)}, green: ${f(rgb.g)}, blue: ${f(rgb.b)}, opacity: ${(token.light.alpha ?? 1).toFixed(3)})\n`
    }
    out += '}\n'
    return out
  },
}

export const flutterEmitter: Emitter = {
  id: 'flutter',
  label: 'Flutter / Dart',
  ext: 'dart',
  language: 'dart',
  hint: 'A class of `Color` constants in ARGB form.',
  emit(graph) {
    const camel = (name: string) =>
      name
        .split('-')
        .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
        .join('')
    let out = header(graph, (t) => `// ${t}`)
    out += "import 'package:flutter/material.dart';\n\nclass PaletteColors {\n  PaletteColors._();\n\n"
    for (const token of graph.tokens) {
      const a = Math.round((token.light.alpha ?? 1) * 255)
        .toString(16)
        .padStart(2, '0')
      out += `  static const Color ${camel(token.name)} = Color(0x${a.toUpperCase()}${hexToken(token.light)});\n`
    }
    out += '}\n'
    return out
  },
}

export const composeEmitter: Emitter = {
  id: 'compose',
  label: 'Jetpack Compose',
  ext: 'kt',
  language: 'kotlin',
  hint: 'Kotlin `val`s of `Color`, ready for a Material theme.',
  emit(graph) {
    const pascal = (name: string) =>
      name
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('')
    let out = header(graph, (t) => `// ${t}`)
    out += 'import androidx.compose.ui.graphics.Color\n\n'
    for (const token of graph.tokens) {
      const a = Math.round((token.light.alpha ?? 1) * 255)
        .toString(16)
        .padStart(2, '0')
      out += `val ${pascal(token.name)} = Color(0x${a.toUpperCase()}${hexToken(token.light)})\n`
    }
    return out
  },
}

/* ------------------------------------------------------------------ *
 * Registry
 * ------------------------------------------------------------------ */

export const shadcnRegistryEmitter: Emitter = {
  id: 'registry',
  label: 'shadcn registry item',
  ext: 'json',
  language: 'json',
  hint: 'A registry item you can host and install with `npx shadcn add <url>`.',
  emit(graph) {
    const { config } = graph
    const light: Record<string, string> = {}
    const dark: Record<string, string> = {}
    for (const token of graph.tokens) {
      light[token.name] = value(token.light, config)
      if (token.dark) dark[token.name] = value(token.dark, config)
    }
    return (
      JSON.stringify(
        {
          $schema: 'https://ui.shadcn.com/schema/registry-item.json',
          name: (graph.title || 'palette').toLowerCase().replace(/\W+/g, '-'),
          type: 'registry:theme',
          cssVars: graph.hasDark ? { theme: {}, light, dark } : { theme: {}, light },
        },
        null,
        2,
      ) + '\n'
    )
  },
}

export const EMITTERS: Emitter[] = [
  cssEmitter,
  tailwind4Emitter,
  tailwind3Emitter,
  scssEmitter,
  lessEmitter,
  jsonEmitter,
  dtcgEmitter,
  tsEmitter,
  csvEmitter,
  svgEmitter,
  gplEmitter,
  androidEmitter,
  swiftEmitter,
  flutterEmitter,
  composeEmitter,
  shadcnRegistryEmitter,
]

export const EMITTERS_BY_ID: Record<string, Emitter> = Object.fromEntries(
  EMITTERS.map((e) => [e.id, e]),
)
